'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
const core=require('..');

const semanticDiff=['diff --git a/src/a.js b/src/a.js','--- a/src/a.js','+++ b/src/a.js','@@ -1 +1 @@','-old','+new','diff --git a/package-lock.json b/package-lock.json','--- a/package-lock.json','+++ b/package-lock.json','@@ -1 +1 @@','-old-lock','+new-lock','diff --git a/images/a.png b/images/a.png','Binary files a/images/a.png and b/images/a.png differ'].join('\n');

test('semantic context keeps source and demotes generated/binary payloads',()=>{const context=core.buildSemanticContext({files:['src/a.js','package-lock.json','images/a.png'],diff:semanticDiff,commits:['feat: x'],maxBytes:4096});assert.match(context.text,/src\/a\.js/);assert.match(context.text,/\+new/);assert.doesNotMatch(context.text,/\+new-lock/);assert.deepEqual(context.generatedFiles,['package-lock.json']);assert.deepEqual(context.binaryFiles,['images/a.png']);assert.equal(core.splitUnifiedDiff(semanticDiff).length,3);});
test('semantic context truncates per source file instead of global prefix slicing',()=>{const large=['diff --git a/src/a.js b/src/a.js','--- a/src/a.js','+++ b/src/a.js','@@ -1 +1 @@',`+${'a'.repeat(6000)}`,'diff --git a/src/b.js b/src/b.js','--- a/src/b.js','+++ b/src/b.js','@@ -1 +1 @@',`+${'b'.repeat(6000)}`].join('\n');const context=core.buildSemanticContext({diff:large,maxBytes:4096});assert.equal(context.truncated,true);assert.deepEqual(context.includedSourceFiles.sort(),['src/a.js','src/b.js']);assert.ok(context.truncatedSourceFiles.length>=1);assert.match(context.text,/src\/a\.js/);assert.match(context.text,/src\/b\.js/);});
test('review evidence chunker preserves every included hunk or fails closed',()=>{const diff=['diff --git a/src/a.js b/src/a.js','--- a/src/a.js','+++ b/src/a.js','@@ -1 +1 @@','-a','+A','@@ -50 +50 @@','-b','+B','diff --git a/src/b.js b/src/b.js','--- a/src/b.js','+++ b/src/b.js','@@ -1 +1 @@','-c','+C'].join('\n');const evidence=core.buildReviewEvidenceChunks({diff,maxBytes:4096,maxChunks:4});assert.equal(evidence.complete,true);assert.match(evidence.chunks.map(c=>c.text).join('\n'),/\+A/);assert.match(evidence.chunks.map(c=>c.text).join('\n'),/\+B/);assert.match(evidence.chunks.map(c=>c.text).join('\n'),/\+C/);const huge=['diff --git a/src/huge.js b/src/huge.js','--- a/src/huge.js','+++ b/src/huge.js','@@ -1 +1 @@',`+${'x'.repeat(6000)}`].join('\n');const incomplete=core.buildReviewEvidenceChunks({diff:huge,maxBytes:4096,maxChunks:2});assert.equal(incomplete.complete,false);assert.ok(incomplete.coverageGaps.some(value=>value.includes('hunk_exceeds_budget')));});
test('policy v4 is canonical, closed and deeply immutable',()=>{assert.equal(core.POLICY_FILE,'.codex-safe.json');assert.equal(core.POLICY_SCHEMA_VERSION,4);const document=core.validatePolicyDocument({schemaVersion:4,commit:{language:'en',scopes:['core'],scopeHints:{core:['runtime']},extraInstructions:'concise'},review:{confidenceThreshold:0.8,severityThreshold:'medium',rules:{requireTestsForCodeChanges:true,codePathPrefixes:['src/'],testPathPrefixes:['test/'],forbiddenPathPrefixes:['secrets/']}},change:{requiredChecks:['build'],requiredApprovals:2,provenancePolicy:'require-all',blockOnReviewFindings:true,requireCleanWorktree:true,requirePushedHead:true,requireFreshTarget:true,reviewers:['alice'],labels:['safe'],titlePolicy:'create-only',managedSections:true},reviewService:{maxContextBytes:65536,maxContextFiles:8,contextLines:20,skipGeneratedFiles:true,blockUnreviewableFiles:false}});assert.equal(document.schemaVersion,4);assert.ok(Object.isFrozen(document));assert.ok(Object.isFrozen(document.change));assert.deepEqual(document.change.requiredChecks,['build']);assert.throws(()=>{document.change.requiredChecks.push('other');},TypeError);assert.throws(()=>core.validatePolicyDocument({schemaVersion:3}),/schemaVersion/);assert.throws(()=>core.validatePolicyDocument({schemaVersion:4,legacy:{}}),/unsupported top-level/);assert.throws(()=>core.validatePolicyDocument({schemaVersion:4,pr:{}}),/unsupported top-level/);assert.throws(()=>core.validatePolicySection('pr',{}),/Unknown policy section/);assert.throws(()=>core.validatePolicySection('commit',{unknown:true}),/unsupported fields/);assert.throws(()=>core.validatePolicySection('review',{confidenceThreshold:1.1}),/between 0 and 1/);assert.throws(()=>core.validatePolicySection('change',{unknown:true}),/unsupported fields/);assert.throws(()=>core.validatePolicySection('change',{requiredApprovals:21}),/between 0 and 20/);assert.throws(()=>core.validatePolicySection('change',{requirePushedHead:'false'}),/boolean/);assert.throws(()=>core.validatePolicySection('change',{requiredChecks:['build','build']}),/duplicate/);assert.throws(()=>core.validatePolicySection('change',{provenancePolicy:'legacy'}),/invalid/);assert.throws(()=>core.validatePolicySection('reviewService',{contextLines:201}),/between 0 and 200/);});
test('JSON Schema keys and critical limits stay aligned with runtime policy',()=>{const schema=JSON.parse(fs.readFileSync(path.join(__dirname,'..','codex-safe.schema.json'),'utf8'));assert.equal(schema.properties.schemaVersion.const,4);for(const section of core.POLICY_SECTIONS){assert.deepEqual(Object.keys(schema.properties[section].properties).sort(),[...core.POLICY_SECTION_KEYS[section]].sort(),`${section} schema keys drifted from runtime`);assert.equal(schema.properties[section].additionalProperties,false);}assert.deepEqual(Object.keys(schema.properties.review.properties.rules.properties).sort(),[...core.REVIEW_RULE_KEYS].sort());assert.equal(schema.properties.change.properties.requiredApprovals.maximum,20);assert.equal(schema.properties.change.properties.provenancePolicy.enum.includes('require-all'),true);assert.equal(schema.properties.pr,undefined);});
test('HEAD policy reader ignores working tree by consuming Git objects only',async()=>{const text=JSON.stringify({schemaVersion:4,change:{requiredChecks:['build']},review:{confidenceThreshold:0.8}}),oid='a'.repeat(40),calls=[];const git=async args=>{calls.push(args);if(args[0]==='ls-tree')return{stdout:`100644 blob ${'b'.repeat(40)}\t.codex-safe.json\0`,stderr:''};if(args[0]==='show')return{stdout:text,stderr:''};throw new Error(`unexpected git call: ${args.join(' ')}`);};const result=await core.readPolicySectionAtHead({git,repoRoot:'/repo',headOid:oid,section:'change'});assert.deepEqual(result.rules,{requiredChecks:['build']});assert.ok(Object.isFrozen(result));assert.ok(Object.isFrozen(result.rules));assert.equal(result.fingerprint,crypto.createHash('sha256').update(text,'utf8').digest('hex'));assert.equal(result.schemaVersion,4);assert.deepEqual(calls[0],['ls-tree','-z',oid,'--','.codex-safe.json']);assert.deepEqual(calls[1],['show',`${oid}:.codex-safe.json`]);});
