'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const{DISPLAY_TIME_ZONE_ENV,resolveDisplayTimeZone,formatDisplayTime,formatLogTimestamp}=require('../display-time');
const{createDiagnosisReceipt,formatDiagnosisMarkdown}=require('../diagnosis-platform');
test('explicit IANA zone changes display only',()=>{const utc='2026-09-02T12:09:00.000Z';assert.equal(formatDisplayTime(utc,{timeZone:'Asia/Singapore'}),'2026-09-02 20:09:00 UTC+08:00');assert.equal(formatDisplayTime(utc,{timeZone:'Asia/Singapore',includeUtc:true}),'2026-09-02 20:09:00 UTC+08:00 (UTC: 2026-09-02T12:09:00.000Z)');});
test('family environment override controls display zone',()=>{const previous=process.env[DISPLAY_TIME_ZONE_ENV];process.env[DISPLAY_TIME_ZONE_ENV]='Asia/Singapore';try{assert.equal(formatLogTimestamp('2026-01-01T00:00:00.000Z'),'2026-01-01 08:00:00 UTC+08:00');}finally{if(previous===undefined)delete process.env[DISPLAY_TIME_ZONE_ENV];else process.env[DISPLAY_TIME_ZONE_ENV]=previous;}});
test('IANA DST rules are honored',()=>{assert.match(formatDisplayTime('2026-07-01T12:00:00.000Z',{timeZone:'America/New_York'}),/UTC-04:00$/);assert.match(formatDisplayTime('2026-01-01T12:00:00.000Z',{timeZone:'America/New_York'}),/UTC-05:00$/);});
test('invalid IANA zone fails closed',()=>assert.throws(()=>resolveDisplayTimeZone('Not/A_Zone'),error=>error.code==='EDISPLAYTIMEZONE'));
test('diagnosis receipt stays UTC while Markdown localizes',()=>{const evidence={digest:'a'.repeat(64),subject:{commitSha:'abc',projectId:1,pipelineId:2,jobId:3}},inputManifest={digest:'b'.repeat(64),promptContractVersion:1},diagnosis={classification:'test',rootCause:'failure',confidence:.8,primaryEvidence:[],relatedFailures:[],affectedFiles:[],recommendedActions:['fix'],retryRecommended:false},receipt=createDiagnosisReceipt({evidence,inputManifest,diagnosis,createdAt:'2026-09-02T12:09:00.000Z'});assert.equal(receipt.createdAt,'2026-09-02T12:09:00.000Z');const previous=process.env[DISPLAY_TIME_ZONE_ENV];process.env[DISPLAY_TIME_ZONE_ENV]='Asia/Singapore';try{const markdown=formatDiagnosisMarkdown(diagnosis,evidence,receipt.createdAt);assert.match(markdown,/\*\*Diagnosis time:\*\* 2026-09-02 20:09:00 UTC\+08:00/);assert.doesNotMatch(markdown,/Diagnosis time \(UTC\)/);}finally{if(previous===undefined)delete process.env[DISPLAY_TIME_ZONE_ENV];else process.env[DISPLAY_TIME_ZONE_ENV]=previous;}});
