'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const{usageShape,extractCodexUsage,estimateRequestTokens,assertWithinTokenBudget,scoreEvidenceRisk,adaptiveBudget,selectModel,selectChunksWithinByteBudget,TokenBudgetLedger}=require('../efficiency-planner');

test('normalizes latest Codex usage from JSONL',()=>{const stdout=[JSON.stringify({type:'turn.completed',usage:{input_tokens:100,cached_input_tokens:30,cache_write_input_tokens:5,output_tokens:20,reasoning_output_tokens:7}}),JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'{}'}})].join('\n');assert.deepEqual(extractCodexUsage(stdout),usageShape({inputTokens:100,cachedInputTokens:30,cacheWriteInputTokens:5,outputTokens:20,reasoningOutputTokens:7}));});
test('preflight estimate is conservative and fail-closed',()=>{const estimate=estimateRequestTokens('x'.repeat(3000),{estimatedOutputTokens:400});assert.ok(estimate.inputTokens>=1500);assert.equal(estimate.totalTokens,estimate.inputTokens+400);assert.throws(()=>assertWithinTokenBudget('x'.repeat(3000),{maxTokens:1000,estimatedOutputTokens:400}),error=>error.code==='ETOKENBUDGET');});
test('risk scoring preserves more budget and can select a fast model',()=>{const low=scoreEvidenceRisk({paths:['docs/readme.md'],text:'+ wording'}),high=scoreEvidenceRisk({paths:['src/auth/token.js'],text:'+ await mutex.lock();\n+ token = secret;'});assert.ok(high>low);assert.ok(adaptiveBudget(100000,high)>adaptiveBudget(100000,low));assert.ok(adaptiveBudget(1000,0,{min:5000})<=1000);assert.equal(selectModel({model:'strong',fastModel:'fast',riskScore:low}),'fast');assert.equal(selectModel({model:'strong',fastModel:'fast',riskScore:high}),'strong');});
test('MR-wide byte budget keeps higher-risk chunks and exposes omissions',()=>{const chunks=[{index:0,bytes:700,paths:['docs/a.md'],text:'+ docs'},{index:1,bytes:700,paths:['src/auth/a.js'],text:'+ token = secret'},{index:2,bytes:700,paths:['src/b.js'],text:'+ value'}],plan=selectChunksWithinByteBudget(chunks,1400);assert.equal(plan.complete,false);assert.equal(plan.chunks.length,2);assert.ok(plan.chunks.some(item=>item.originalIndex===1));assert.deepEqual(plan.chunks.map(item=>item.index),[0,1]);assert.equal(plan.omitted.length,1);});
test('reservation ledger prevents concurrent overshoot',()=>{const ledger=new TokenBudgetLedger();ledger.reserve('a',7,60,{budget:100,committed:20});assert.throws(()=>ledger.reserve('b',7,30,{budget:100,committed:20}),error=>error.code==='ETOKENBUDGET');assert.equal(ledger.release('a'),60);ledger.reserve('b',7,30,{budget:100,committed:20});assert.equal(ledger.reservedForProject(7),30);});
