'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
const core=require('../core-contract.json');
const registry=require('../family-registry.json');
const {readSnapshot}=require('../scripts/checkout-family-snapshot');
const {validateRelease}=require('../scripts/verify-released-core');
const {verify:verifyProductContract}=require('../scripts/verify-consumer-product-contract');
const {bumpPatch}=require('../scripts/repin-consumer');
const {consumerHeadIsAligned,evaluateFreshness,manifestMatches,releaseIsExact}=require('../scripts/family-freshness');

function digest(value){return crypto.createHash('sha256').update(String(value)).digest('hex');}
function productFixture(productId){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'codex-safe-product-')),pin='d'.repeat(40);execFileSync('git',['init','-q'],{cwd:dir});fs.mkdirSync(path.join(dir,'src'),{recursive:true});fs.writeFileSync(path.join(dir,'package.json'),JSON.stringify({version:'9.9.9'}));fs.writeFileSync(path.join(dir,'product-contract.json'),JSON.stringify({productContractVersion:core.productContractVersion,productId,productVersion:'9.9.9',safeCoreVersion:core.coreVersion,safeCoreMajorVersion:core.safeCoreMajorVersion,safeContractVersion:core.safeContractVersion,policySchemaVersion:core.policySchemaVersion,safeCoreCommit:pin,minimumNodeVersion:core.minimumNodeVersion,canonicalNodeVersion:core.canonicalNodeVersion,supportedNodeMajors:core.supportedNodeMajors}));execFileSync('git',['update-index','--add','--cacheinfo',`160000,${pin},src/codex-safe-core`],{cwd:dir});return{dir,pin};}
function release(version,sha){return{tag:`v${version}`,tagSha:sha,immutable:true,publishedAt:'2026-09-03T00:00:00Z',assets:[]};}
function distribution(){return{ready:true,channel:'github-release',reason:'release-is-distribution'};}
function alignedFamilyState(){const coreSha='a'.repeat(40),coreState={version:core.coreVersion,sha:coreSha,releaseReady:true,release:release(core.coreVersion,coreSha),reason:'exact-immutable-release'},consumers={};for(const [index,name] of Object.keys(registry.consumers).entries()){const sha=String(index+1).repeat(40).slice(0,40),version=`1.${index}.0`;consumers[name]={sha,version,aligned:true,releaseReady:true,distributionReady:true,ready:true,release:release(version,sha),distribution:distribution(),reason:'exact-release-and-distribution'};}return{core:coreState,consumers};}

test('Family contract versions are release-aware',()=>{assert.equal(core.familyRegistryVersion,1);assert.equal(core.familySnapshotVersion,2);assert.equal(core.familyManifestVersion,4);assert.equal(core.familyStatusVersion,1);assert.equal(core.distributionReceiptVersion,1);assert.equal(registry.schemaVersion,core.familyRegistryVersion);});
test('atomic Family snapshot v2 digest fails closed on mutation',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'codex-safe-snapshot-')),file=path.join(dir,'snapshot.json'),base={schemaVersion:core.familySnapshotVersion,registry:{schemaVersion:registry.schemaVersion,digest:digest(JSON.stringify(registry))},core:{version:core.coreVersion,sha:'a'.repeat(40),release:release(core.coreVersion,'a'.repeat(40))},consumers:{'codex-commit':{sha:'b'.repeat(40),version:'1.0.0',release:release('1.0.0','b'.repeat(40)),distribution:distribution()}}};const value={...base,snapshotDigest:digest(JSON.stringify(base))};fs.writeFileSync(file,JSON.stringify(value));assert.equal(readSnapshot(file).snapshotDigest,value.snapshotDigest);value.core.sha='c'.repeat(40);fs.writeFileSync(file,JSON.stringify(value));assert.throws(()=>readSnapshot(file),/digest/i);fs.rmSync(dir,{recursive:true,force:true});});
test('released Core validator requires exact immutable final release',()=>{assert.equal(validateRelease({tag_name:`v${core.coreVersion}`,draft:false,prerelease:false,immutable:true},{tag:`v${core.coreVersion}`,sha:'a'.repeat(40),expectedSha:'a'.repeat(40)}),true);assert.throws(()=>validateRelease({tag_name:`v${core.coreVersion}`,draft:false,prerelease:false,immutable:false},{tag:`v${core.coreVersion}`,sha:'a'.repeat(40),expectedSha:'a'.repeat(40)}),/not immutable/);});
test('consumer Product Contract v1 binds package identity and Core gitlink',()=>{const {dir,pin}=productFixture('codex-review-safe');assert.equal(verifyProductContract(dir,pin,'codex-review-safe').safeCoreCommit,pin);fs.rmSync(dir,{recursive:true,force:true});});
test('consumer Product Contract v1 accepts the active Change product',()=>{const {dir,pin}=productFixture('codex-change-safe');assert.equal(verifyProductContract(dir,pin,'codex-change-safe').productId,'codex-change-safe');fs.rmSync(dir,{recursive:true,force:true});});
test('Core repin product version uses mandatory patch bump',()=>{assert.equal(bumpPatch('4.7.2'),'4.7.3');assert.equal(bumpPatch('7.4.1'),'7.4.2');assert.throws(()=>bumpPatch('4.7'),/MAJOR\.MINOR\.PATCH/);});
test('Family freshness accepts only exact immutable release/tag/main identity',()=>{const sha='a'.repeat(40),tag='v1.2.3';assert.equal(releaseIsExact({tag_name:tag,draft:false,prerelease:false,immutable:true},{tag,headSha:sha,tagSha:sha}),true);assert.equal(releaseIsExact({tag_name:tag,draft:false,prerelease:false,immutable:false},{tag,headSha:sha,tagSha:sha}),false);assert.equal(releaseIsExact({tag_name:tag,draft:false,prerelease:false,immutable:true},{tag,headSha:sha,tagSha:'b'.repeat(40)}),false);});
test('consumer Core alignment alone is insufficient for Family freshness',()=>{const coreState={version:'4.14.0',sha:'a'.repeat(40)},state={sha:'b'.repeat(40),version:'7.4.2',corePin:{type:'submodule',sha:'a'.repeat(40),submodule_git_url:'https://github.com/jiying2007/codex-safe-core.git'},productContract:{productContractVersion:core.productContractVersion,productVersion:'7.4.2',safeCoreVersion:'4.14.0',safeCoreCommit:'a'.repeat(40)}};assert.equal(consumerHeadIsAligned(state,coreState),true);const family=alignedFamilyState();family.consumers['codex-review-service']={...family.consumers['codex-review-service'],aligned:true,releaseReady:false,distributionReady:false,ready:false,reason:'consumer-release-not-exact'};const decision=evaluateFreshness({...family,manifest:null});assert.equal(decision.ready,false);assert.equal(decision.dispatch,false);assert.match(decision.reason,/consumer-release-not-exact/);});
test('Family freshness blocks when distribution receipt is missing',()=>{const state=alignedFamilyState();state.consumers['codex-review']={...state.consumers['codex-review'],distributionReady:false,ready:false,reason:'distribution-not-ready'};const decision=evaluateFreshness({...state,manifest:null});assert.equal(decision.ready,false);assert.match(decision.reason,/distribution-not-ready/);});
test('Family freshness suppresses duplicate dispatch while authoritative validation is active',()=>{const state=alignedFamilyState(),decision=evaluateFreshness({...state,manifest:null,validationActive:true});assert.equal(decision.ready,true);assert.equal(decision.dispatch,false);assert.equal(decision.reason,'family-validation-active');});
test('Family Manifest v4 identity includes exact release and distribution evidence',()=>{const state=alignedFamilyState(),manifest={schemaVersion:core.familyManifestVersion,core:{version:state.core.version,sha:state.core.sha,release:state.core.release},consumers:Object.fromEntries(Object.entries(state.consumers).map(([name,value])=>[name,{sha:value.sha,version:value.version,release:value.release,distribution:value.distribution}]))};assert.equal(manifestMatches(manifest,state),true);manifest.consumers['codex-review'].release.tagSha='f'.repeat(40);assert.equal(manifestMatches(manifest,state),false);});
test('Family freshness workflow is same-repository, credential-minimal and CI-lightweight',()=>{const workflow=fs.readFileSync(path.join(__dirname,'..','.github','workflows','family-freshness.yml'),'utf8');assert.match(workflow,/actions:\s*write/);assert.match(workflow,/contents:\s*read/);assert.match(workflow,/family-ci\.yml/);assert.match(workflow,/17,47 \* \* \* \*/);assert.doesNotMatch(workflow,/FAMILY_BOT_TOKEN/);assert.doesNotMatch(workflow,/npm run ci/);});
