'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
const core=require('../core-contract.json');
const {readSnapshot}=require('../scripts/checkout-family-snapshot');
const {validateRelease}=require('../scripts/verify-released-core');
const {verify:verifyProductContract}=require('../scripts/verify-consumer-product-contract');
const {evaluateFreshness,manifestMatches,releaseIsExact}=require('../scripts/family-freshness');

function digest(value){return crypto.createHash('sha256').update(String(value)).digest('hex');}
function productFixture(productId){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'codex-safe-product-')),pin='d'.repeat(40);execFileSync('git',['init','-q'],{cwd:dir});fs.mkdirSync(path.join(dir,'src'),{recursive:true});fs.writeFileSync(path.join(dir,'package.json'),JSON.stringify({version:'9.9.9'}));fs.writeFileSync(path.join(dir,'product-contract.json'),JSON.stringify({productContractVersion:core.productContractVersion,productId,productVersion:'9.9.9',safeCoreVersion:core.coreVersion,safeCoreMajorVersion:core.safeCoreMajorVersion,safeContractVersion:core.safeContractVersion,policySchemaVersion:core.policySchemaVersion,safeCoreCommit:pin,minimumNodeVersion:core.minimumNodeVersion,canonicalNodeVersion:core.canonicalNodeVersion,supportedNodeMajors:core.supportedNodeMajors}));execFileSync('git',['update-index','--add','--cacheinfo',`160000,${pin},src/codex-safe-core`],{cwd:dir});return{dir,pin};}
function releasedFamilyState(){const consumers={};for(const [index,name] of ['codex-pr','codex-commit','codex-review','codex-review-service','codex-diagnose'].entries())consumers[name]={sha:String(index+1).repeat(40).slice(0,40),version:`1.${index}.0`,releaseReady:true,reason:'exact-immutable-release'};return{core:{version:core.coreVersion,sha:'a'.repeat(40),releaseReady:true,reason:'exact-immutable-release'},consumers};}
test('atomic Family snapshot digest fails closed on mutation',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'codex-safe-snapshot-')),file=path.join(dir,'snapshot.json'),base={schemaVersion:core.familySnapshotVersion,core:{version:core.coreVersion,sha:'a'.repeat(40)},consumers:{'codex-commit':{sha:'b'.repeat(40)}}};const value={...base,snapshotDigest:digest(JSON.stringify(base))};fs.writeFileSync(file,JSON.stringify(value));assert.equal(readSnapshot(file).snapshotDigest,value.snapshotDigest);value.core.sha='c'.repeat(40);fs.writeFileSync(file,JSON.stringify(value));assert.throws(()=>readSnapshot(file),/digest/i);fs.rmSync(dir,{recursive:true,force:true});});
test('released Core validator requires exact immutable final release',()=>{assert.equal(validateRelease({tag_name:`v${core.coreVersion}`,draft:false,prerelease:false,immutable:true},{tag:`v${core.coreVersion}`,sha:'a'.repeat(40),expectedSha:'a'.repeat(40)}),true);assert.throws(()=>validateRelease({tag_name:`v${core.coreVersion}`,draft:false,prerelease:false,immutable:false},{tag:`v${core.coreVersion}`,sha:'a'.repeat(40),expectedSha:'a'.repeat(40)}),/not immutable/);assert.throws(()=>validateRelease({tag_name:`v${core.coreVersion}`,draft:false,prerelease:false,immutable:true},{tag:`v${core.coreVersion}`,sha:'b'.repeat(40),expectedSha:'a'.repeat(40)}),/expected/);});
test('consumer Product Contract v1 binds package identity and Core gitlink',()=>{const {dir,pin}=productFixture('codex-review-safe');assert.equal(verifyProductContract(dir,pin,'codex-review-safe').safeCoreCommit,pin);fs.rmSync(dir,{recursive:true,force:true});});
test('consumer Product Contract v1 accepts the active Change product',()=>{const {dir,pin}=productFixture('codex-change-safe');assert.equal(verifyProductContract(dir,pin,'codex-change-safe').productId,'codex-change-safe');fs.rmSync(dir,{recursive:true,force:true});});
test('Family freshness accepts only exact immutable release/tag/main identity',()=>{const sha='a'.repeat(40),tag='v1.2.3';assert.equal(releaseIsExact({tag_name:tag,draft:false,prerelease:false,immutable:true},{tag,headSha:sha,tagSha:sha}),true);assert.equal(releaseIsExact({tag_name:tag,draft:false,prerelease:false,immutable:false},{tag,headSha:sha,tagSha:sha}),false);assert.equal(releaseIsExact({tag_name:tag,draft:false,prerelease:false,immutable:true},{tag,headSha:sha,tagSha:'b'.repeat(40)}),false);});
test('Family freshness does not dispatch while any active released head is not ready',()=>{const state=releasedFamilyState();state.consumers['codex-review-service']={...state.consumers['codex-review-service'],releaseReady:false,reason:'main-not-exact-immutable-release'};const decision=evaluateFreshness({...state,manifest:null});assert.equal(decision.ready,false);assert.equal(decision.dispatch,false);assert.match(decision.reason,/codex-review-service/);});
test('Family freshness dispatches only for a released snapshot missing from the immutable manifest',()=>{const state=releasedFamilyState();const stale=evaluateFreshness({...state,manifest:null});assert.equal(stale.ready,true);assert.equal(stale.dispatch,true);assert.equal(stale.reason,'family-manifest-missing');const manifest={schemaVersion:core.familyManifestVersion,core:{version:state.core.version,sha:state.core.sha},consumers:Object.fromEntries(Object.entries(state.consumers).map(([name,value])=>[name,{sha:value.sha,version:value.version}]))};assert.equal(manifestMatches(manifest,state),true);const current=evaluateFreshness({...state,manifest});assert.equal(current.dispatch,false);assert.equal(current.reason,'family-manifest-current');manifest.consumers['codex-review-service'].sha='f'.repeat(40);const changed=evaluateFreshness({...state,manifest});assert.equal(changed.dispatch,true);assert.equal(changed.reason,'family-manifest-stale');});
test('Family freshness workflow is same-repository, credential-minimal and CI-lightweight',()=>{const workflow=fs.readFileSync(path.join(__dirname,'..','.github','workflows','family-freshness.yml'),'utf8');assert.match(workflow,/actions:\s*write/);assert.match(workflow,/contents:\s*read/);assert.match(workflow,/family-ci\.yml/);assert.match(workflow,/17,47 \* \* \* \*/);assert.doesNotMatch(workflow,/FAMILY_BOT_TOKEN/);assert.doesNotMatch(workflow,/npm run ci/);});
