'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const {resolveReviewProfile,extractImpactSignals,buildImpactEvidenceGraph,normalizeSarif,formatAnalyzerEvidence,evaluateQualityResults,assertQualityGate,validatePatchProposal,comparePerformanceSnapshot}=require('../quality-platform');

test('review profiles are deterministic and cap-preserving inputs',()=>{assert.equal(resolveReviewProfile('quick').impactDepth,0);assert.equal(resolveReviewProfile('embedded').name,'embedded');assert.equal(resolveReviewProfile('unknown').name,'standard');assert.equal(resolveReviewProfile('deep',{contextFactor:2}).contextFactor,1);});

test('impact evidence finds includes, symbols, config and build references',()=>{const diff=['diff --git a/src/motor.c b/src/motor.c','--- a/src/motor.c','+++ b/src/motor.c','@@ -1 +1,4 @@','+#include "motor_ctrl.h"','+int motor_set_speed(int rpm) { return rpm; }','+#if CONFIG_MOTOR_SAFE','+motor_set_speed(10);'].join('\n');const signals=extractImpactSignals(diff);assert.ok(signals.includes.includes('motor_ctrl.h'));assert.ok(signals.symbols.includes('motor_set_speed'));assert.ok(signals.configs.includes('CONFIG_MOTOR_SAFE'));const graph=buildImpactEvidenceGraph({diff,candidates:[{path:'include/motor_ctrl.h',content:'int motor_set_speed(int rpm);'},{path:'src/app.c',content:'void app(){ motor_set_speed(1); }'},{path:'README.md',content:'nothing'}],maxNodes:4,maxBytes:4096});assert.ok(graph.nodes.some(node=>node.path==='include/motor_ctrl.h'));assert.ok(graph.nodes.some(node=>node.path==='src/app.c'));assert.ok(graph.text.includes('IMPACT EVIDENCE GRAPH'));});

test('SARIF is normalized into analyzer finding contract',()=>{const findings=normalizeSarif({version:'2.1.0',runs:[{tool:{driver:{name:'Semgrep',rules:[{id:'c.injection',properties:{tags:['security']}}]}},results:[{ruleId:'c.injection',level:'error',message:{text:'unsafe command construction'},locations:[{physicalLocation:{artifactLocation:{uri:'src/cmd.c'},region:{startLine:7}}}],partialFingerprints:{primaryLocationLineHash:'abc'}}]}]});assert.equal(findings.length,1);assert.equal(findings[0].tool,'Semgrep');assert.equal(findings[0].category,'security');assert.equal(findings[0].file,'src/cmd.c');assert.equal(findings[0].line,7);const evidence=formatAnalyzerEvidence(findings,{maxFindings:10,maxBytes:4096});assert.equal(evidence.included,1);assert.match(evidence.text,/unsafe command/);});

test('quality eval locks critical recall and cost-quality metrics',()=>{const cases=[{id:'a',expected:[{severity:'critical',category:'security',file:'a.c',line:4}]},{id:'b',expected:[{severity:'high',category:'concurrency',file:'b.c',line:8}]}],results=[{id:'a',findings:[{severity:'critical',category:'security',file:'a.c',line:4,fingerprint:'a'}],usage:{inputTokens:100,outputTokens:20}},{id:'b',findings:[{severity:'high',category:'concurrency',file:'b.c',line:8,fingerprint:'b'}],usage:{inputTokens:80,outputTokens:20}}],metrics=evaluateQualityResults(cases,results);assert.equal(metrics.criticalRecall,1);assert.equal(metrics.recall,1);assert.equal(metrics.precision,1);assert.doesNotThrow(()=>assertQualityGate(metrics,{minRecall:1,minPrecision:1}));assert.throws(()=>assertQualityGate({...metrics,criticalRecall:0},{minCriticalRecall:1}),/Quality gate failed/);});

test('patch proposal cannot escape reviewed paths',()=>{const patch='diff --git a/src/a.c b/src/a.c\n--- a/src/a.c\n+++ b/src/a.c\n@@ -1 +1 @@\n-old\n+new\n',value=validatePatchProposal({patch,rationale:'fix'},{allowedPaths:['src/a.c']});assert.deepEqual(value.touchedPaths,['src/a.c']);assert.throws(()=>validatePatchProposal({patch:patch.replaceAll('src/a.c','src/b.c')},{allowedPaths:['src/a.c']}),/outside reviewed evidence/);});

test('relative performance regression comparison is deterministic',()=>{assert.equal(comparePerformanceSnapshot({latencyMs:105,rssBytes:100,artifactBytes:100},{latencyMs:100,rssBytes:100,artifactBytes:100}).ok,true);assert.equal(comparePerformanceSnapshot({latencyMs:120,rssBytes:100,artifactBytes:100},{latencyMs:100,rssBytes:100,artifactBytes:100}).ok,false);});
