'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const core=require('..');

function reviewReceipt(overrides={}){return{schemaVersion:5,kind:'codex-review',subject:{type:'git-index',headOid:'1'.repeat(40),indexFingerprint:'2'.repeat(64),stagedFileCount:1},diffFingerprint:'3'.repeat(64),policyFingerprint:'4'.repeat(64),reviewSubjectFingerprint:'5'.repeat(64),evidenceManifestDigest:'6'.repeat(64),qualityVerdict:'no_findings',readinessVerdict:'needs_evidence',mechanicalGate:'not_run',coverageVerdict:'complete',model:'gpt-test',codexVersion:'codex-cli 1.0.0',createdAt:'2026-08-22T00:00:00.000Z',...overrides};}
function serviceReviewReceipt(overrides={}){return reviewReceipt({subject:{type:'gitlab-mr',projectId:7,mrIid:9,startSha:'a'.repeat(40),headSha:'b'.repeat(40)},...overrides});}
function commitReceipt(overrides={}){return{schemaVersion:4,kind:'codex-commit-safe',headOid:'1'.repeat(40),indexFingerprint:'2'.repeat(64),diffFingerprint:'3'.repeat(64),messageFingerprint:'4'.repeat(64),policyFingerprint:'5'.repeat(64),reviewReceiptFingerprint:'<none>',model:'gpt-test',codexVersion:'codex-cli 1.0.0',createdAt:'2026-08-22T00:00:00.000Z',commitOid:'<pending>',...overrides};}

test('contract versions and required Codex arguments stay hard-pinned',()=>{assert.equal(core.SAFE_CORE_VERSION,4);assert.equal(core.SAFE_CONTRACT_VERSION,2);assert.equal(core.CURRENT_POLICY_SCHEMA_VERSION,4);assert.equal(core.REVIEW_RECEIPT_SCHEMA_VERSION,5);assert.equal(core.COMMIT_RECEIPT_SCHEMA_VERSION,4);assert.equal(core.REVIEW_PROMPT_CONTRACT_VERSION,1);assert.equal(core.COMMIT_PROMPT_CONTRACT_VERSION,1);const args=core.buildSafeCodexArgs('/tmp/schema.json','model-x');assert.ok(args.indexOf('--ask-for-approval')<args.indexOf('exec'));assert.equal(args[args.indexOf('--ask-for-approval')+1],'never');assert.equal(args[args.indexOf('--sandbox')+1],'read-only');assert.ok(args.includes('--ignore-user-config'));assert.ok(args.includes('--ignore-rules'));assert.ok(args.includes('--output-schema'));});
test('review receipt v5 binds judgment subject and evidence identity',()=>{const receipt=core.validateReviewReceipt(reviewReceipt());assert.ok(receipt);assert.equal(receipt.safeCoreVersion,4);assert.equal(receipt.safeContractVersion,2);assert.equal(receipt.policySchemaVersion,4);assert.equal(receipt.promptContractVersion,1);assert.equal(receipt.requestedModel,'gpt-test');assert.equal(receipt.resolvedModel,'gpt-test');assert.ok(core.validateReviewReceipt(serviceReviewReceipt()));assert.equal(core.validateReviewReceipt(reviewReceipt({schemaVersion:4})),null);assert.equal(core.validateReviewReceipt(reviewReceipt({reviewSubjectFingerprint:''})),null);assert.equal(core.validateReviewReceipt(reviewReceipt({evidenceManifestDigest:'bad'})),null);assert.equal(core.validateReviewReceipt(reviewReceipt({safeCoreVersion:3})),null);assert.equal(core.validateReviewReceipt(reviewReceipt({policySchemaVersion:3})),null);assert.equal(core.validateReviewReceipt(reviewReceipt({promptContractVersion:2})),null);assert.equal(core.validateReviewReceipt(reviewReceipt({kind:'codex-review-safe'})),null);assert.equal(core.validateReviewReceipt(reviewReceipt({unknown:true})),null);assert.equal(core.validateReviewReceipt(reviewReceipt({createdAt:'2026-08-22'})),null);assert.equal(core.validateReviewReceipt(reviewReceipt({coverageVerdict:'unknown'})),null);assert.equal(core.validateReviewReceipt(reviewReceipt({subject:{type:'git-index',headOid:'1'.repeat(40),indexFingerprint:'2'.repeat(64),stagedFileCount:5001}})),null);assert.equal(core.validateReviewReceipt(serviceReviewReceipt({subject:{type:'gitlab-mr',projectId:0,mrIid:9,startSha:'a'.repeat(40),headSha:'b'.repeat(40)}})),null);});
test('commit receipt is a closed v4 contract with canonical provenance',()=>{const receipt=core.validateCommitReceipt(commitReceipt());assert.ok(receipt);assert.equal(receipt.safeCoreVersion,4);assert.equal(receipt.policySchemaVersion,4);assert.equal(receipt.promptContractVersion,1);assert.ok(core.validateCommitReceipt(commitReceipt({commitOid:'a'.repeat(40)})));assert.equal(core.validateCommitReceipt(commitReceipt({schemaVersion:3})),null);assert.equal(core.validateCommitReceipt(commitReceipt({policySchemaVersion:3})),null);assert.equal(core.validateCommitReceipt(commitReceipt({unknown:true})),null);assert.equal(core.validateCommitReceipt(commitReceipt({commitOid:'-bad'})),null);});
test('fingerprints are stable across object key order',()=>{assert.equal(core.fingerprint({a:1,b:{c:2}}),core.fingerprint({b:{c:2},a:1}));assert.match(core.fingerprint({a:1}),/^[0-9a-f]{64}$/);});
test('capability helper reports missing flags and compatibility failures',()=>{assert.deepEqual(core.missingHelpFlags('x --json y',['--json','--sandbox']),['--sandbox']);assert.equal(core.isCliCompatibilityError({stderr:'error: unknown config key foo'}),true);assert.equal(core.isCliCompatibilityError({stderr:'authentication failed'}),false);});
