'use strict';

const USAGE_KEYS=Object.freeze(['inputTokens','cachedInputTokens','cacheWriteInputTokens','outputTokens','reasoningOutputTokens']);
const SEVERITY_RISK_PATTERNS=Object.freeze({
  highPaths:[/(^|\/)(auth|security|crypto|secrets?|permissions?|iam)(\/|\.|$)/i,/(^|\/)(migrations?|schema)(\/|\.|$)/i,/\.(c|cc|cpp|cxx|h|hh|hpp|rs)$/i],
  mediumPaths:[/(^|\/)(api|db|database|storage|network|http|runner|worker|scheduler|runtime)(\/|\.|$)/i,/Dockerfile$/i,/\.ya?ml$/i],
  highText:/\b(mutex|semaphore|atomic|lock|race|deadlock|use-after-free|double[- ]free|malloc|calloc|realloc|free\s*\(|password|secret|token|signature|authorization|authentication|sql|transaction|rollback|exec\s*\(|spawn\s*\(|eval\s*\(|deserialize|prototype pollution)\b/i,
  mediumText:/\b(timeout|retry|cache|stream|socket|file descriptor|promise|async|await|thread|process|memory|resource|permission|migration|schema|api|backward compat|breaking)\b/i
});

function byteLength(value){return Buffer.byteLength(String(value||''),'utf8');}
function usageShape(value={}){return Object.freeze({inputTokens:Number(value.input_tokens??value.inputTokens??0)||0,cachedInputTokens:Number(value.cached_input_tokens??value.cachedInputTokens??0)||0,cacheWriteInputTokens:Number(value.cache_write_input_tokens??value.cacheWriteInputTokens??0)||0,outputTokens:Number(value.output_tokens??value.outputTokens??0)||0,reasoningOutputTokens:Number(value.reasoning_output_tokens??value.reasoningOutputTokens??0)||0});}
function usageAdd(total={},next={}){for(const key of USAGE_KEYS)total[key]=(Number(total[key])||0)+(Number(next[key])||0);return total;}
function usageTotal(usage={}){return (Number(usage.inputTokens)||0)+(Number(usage.outputTokens)||0);}
function extractCodexUsage(stdout){let usage=usageShape();for(const line of String(stdout||'').split(/\r?\n/).filter(Boolean)){let event;try{event=JSON.parse(line);}catch{continue;}if(event?.type==='turn.completed'&&event.usage)usage=usageShape(event.usage);}return usage;}
function estimateTextTokens(value,bytesPerToken=2){const divisor=Math.max(1,Number(bytesPerToken)||2);return Math.max(1,Math.ceil(byteLength(value)/divisor));}
function estimateRequestTokens(input,{estimatedOutputTokens=512,bytesPerToken=2}={}){const inputTokens=estimateTextTokens(input,bytesPerToken),outputTokens=Math.max(0,Math.ceil(Number(estimatedOutputTokens)||0));return Object.freeze({inputTokens,outputTokens,totalTokens:inputTokens+outputTokens,bytes:byteLength(input)});}
function assertWithinTokenBudget(input,{maxTokens=0,estimatedOutputTokens=512,bytesPerToken=2,label='Codex request'}={}){const estimate=estimateRequestTokens(input,{estimatedOutputTokens,bytesPerToken});if(Number(maxTokens)>0&&estimate.totalTokens>Number(maxTokens)){const error=new Error(`${label} estimated token budget exceeded: ${estimate.totalTokens} > ${maxTokens}`);error.code='ETOKENBUDGET';error.estimate=estimate;error.maxTokens=Number(maxTokens);throw error;}return estimate;}

function scoreEvidenceRisk({paths=[],text=''}={}){let score=0;for(const raw of paths||[]){const path=String(raw||'').replace(/\\/g,'/');if(SEVERITY_RISK_PATTERNS.highPaths.some(pattern=>pattern.test(path)))score+=5;else if(SEVERITY_RISK_PATTERNS.mediumPaths.some(pattern=>pattern.test(path)))score+=2;if(/(^|\/)(test|tests|fixtures?|docs?)(\/|\.|$)/i.test(path))score-=1;}const source=String(text||'');if(SEVERITY_RISK_PATTERNS.highText.test(source))score+=5;if(SEVERITY_RISK_PATTERNS.mediumText.test(source))score+=2;const changedLines=(source.match(/^[+-](?![+-])/gm)||[]).length;if(changedLines>300)score+=2;else if(changedLines>100)score+=1;return Math.max(0,score);}
function adaptiveBudget(cap,riskScore,{lowFactor=0.25,mediumFactor=0.5,min=0}={}){const limit=Math.max(0,Math.floor(Number(cap)||0));if(!limit)return 0;const factor=Number(riskScore)>=8?1:Number(riskScore)>=4?mediumFactor:lowFactor;const desired=Math.floor(limit*Math.max(0,Math.min(1,Number(factor)||0)));return Math.min(limit,Math.max(Math.min(limit,Math.max(0,Math.floor(Number(min)||0))),desired));}
function selectModel({model='',fastModel='',riskScore=0,fastThreshold=4}={}){const fast=String(fastModel||'').trim();if(fast&&Number(riskScore)<Number(fastThreshold))return fast;return String(model||'').trim();}
function selectChunksWithinByteBudget(chunks,maxBytes,{riskFn=chunk=>scoreEvidenceRisk({paths:chunk?.paths||chunk?.files?.map(file=>file?.path)||[],text:chunk?.text||chunk?.diffText||''})}={}){const values=Array.isArray(chunks)?chunks:[],budget=Math.max(0,Math.floor(Number(maxBytes)||0)),total=values.reduce((sum,item)=>sum+(Number(item?.bytes)||byteLength(item?.text||item?.diffText||'')),0);if(!budget||total<=budget)return Object.freeze({chunks:Object.freeze(values.slice()),omitted:Object.freeze([]),bytes:total,complete:true});const ranked=values.map((chunk,index)=>({chunk,index,risk:Number(riskFn(chunk))||0,size:Number(chunk?.bytes)||byteLength(chunk?.text||chunk?.diffText||'')})).sort((a,b)=>b.risk-a.risk||a.index-b.index),selected=[],omitted=[];let bytes=0;for(const item of ranked){if(item.size<=budget-bytes){selected.push(item);bytes+=item.size;}else omitted.push(item);}selected.sort((a,b)=>a.index-b.index);omitted.sort((a,b)=>a.index-b.index);const planned=selected.map((item,index)=>Object.freeze({...item.chunk,originalIndex:item.chunk.index??item.index,index}));return Object.freeze({chunks:Object.freeze(planned),omitted:Object.freeze(omitted.map(item=>item.chunk)),bytes,complete:omitted.length===0});}

class TokenBudgetLedger{
  constructor(){this.byKey=new Map();this.byProject=new Map();}
  reservedForProject(projectId){return Number(this.byProject.get(String(projectId))||0);}
  reservedForKey(key){return Number(this.byKey.get(String(key))?.tokens||0);}
  reserve(key,projectId,tokens,{budget=0,committed=0}={}){const amount=Math.max(0,Math.ceil(Number(tokens)||0));if(!amount)return this.reservedForKey(key);const id=String(key),project=String(projectId),current=this.byKey.get(id)||{projectId:project,tokens:0};if(current.projectId!==project)throw new Error('Token reservation project mismatch');const reserved=this.reservedForProject(project);if(Number(budget)>0&&Number(committed||0)+reserved+amount>Number(budget)){const error=new Error('Token budget would be exceeded by the next reservation');error.code='ETOKENBUDGET';error.committed=Number(committed||0);error.reserved=reserved;error.requested=amount;error.budget=Number(budget);throw error;}current.tokens+=amount;this.byKey.set(id,current);this.byProject.set(project,reserved+amount);return current.tokens;}
  release(key){const id=String(key),current=this.byKey.get(id);if(!current)return 0;const reserved=this.reservedForProject(current.projectId),remaining=Math.max(0,reserved-current.tokens);if(remaining)this.byProject.set(current.projectId,remaining);else this.byProject.delete(current.projectId);this.byKey.delete(id);return current.tokens;}
}

module.exports={USAGE_KEYS,usageShape,usageAdd,usageTotal,extractCodexUsage,estimateTextTokens,estimateRequestTokens,assertWithinTokenBudget,scoreEvidenceRisk,adaptiveBudget,selectModel,selectChunksWithinByteBudget,TokenBudgetLedger};
