'use strict';

const crypto = require('node:crypto');

const TEST_IMPACT_VERSION = 1;
function freeze(value){if(Array.isArray(value))return Object.freeze(value.map(freeze));if(value&&typeof value==='object')return Object.freeze(Object.fromEntries(Object.entries(value).map(([k,v])=>[k,freeze(v)])));return value;}
function normalizePath(value){return String(value||'').replace(/\\/g,'/').replace(/^\.\//,'').replace(/^a\//,'').replace(/^b\//,'');}
function basename(value){const path=normalizePath(value);return path.slice(path.lastIndexOf('/')+1);}
function stem(value){const base=basename(value),index=base.lastIndexOf('.');return(index>0?base.slice(0,index):base).toLowerCase().replace(/(?:_test|test_|\.test|\.spec)$/,'');}
function sha(value){return crypto.createHash('sha256').update(String(value)).digest('hex');}
function escaped(value){return String(value).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function normalizeTestCandidate(raw={}){const path=normalizePath(raw.path||raw.file),id=String(raw.id||raw.name||path).trim().slice(0,512),content=String(raw.content||''),relatedPaths=Array.isArray(raw.relatedPaths)?raw.relatedPaths.map(normalizePath).filter(Boolean):[];if(!id||!path)return null;return freeze({id,path,content,relatedPaths:[...new Set(relatedPaths)]});}
function candidateScore(candidate,changedPaths,signals={},history={}){let score=0;const reasons=[];const hit=(points,reason)=>{score+=points;reasons.push(reason);};const low=candidate.path.toLowerCase(),candidateStem=stem(candidate.path);for(const changed of changedPaths){const normalized=normalizePath(changed),changedStem=stem(normalized);if(candidate.relatedPaths.includes(normalized))hit(100,'explicit-related-path');if(changedStem&&candidateStem&&changedStem===candidateStem)hit(55,'same-stem');const dir=normalized.includes('/')?normalized.slice(0,normalized.lastIndexOf('/')):'';if(dir&&low.startsWith(`${dir.toLowerCase()}/`))hit(18,'same-directory');if(candidate.content&&candidate.content.includes(basename(normalized)))hit(28,'changed-file-reference');}
for(const symbol of signals.symbols||[]){if(candidate.content&&new RegExp(`\\b${escaped(symbol)}\\b`).test(candidate.content)){hit(12,'changed-symbol-reference');break;}}
for(const moduleName of signals.modules||[]){const normalized=String(moduleName).replace(/^\.\//,'').replace(/\./g,'/');if(normalized&&(low.includes(normalized.toLowerCase())||candidate.content.includes(moduleName))){hit(16,'changed-module-reference');break;}}
const historical=Number(history[candidate.id]??history[candidate.path]??0);if(Number.isFinite(historical)&&historical>0)hit(Math.min(50,Math.round(historical*10)),'historical-failure-correlation');return{score,reasons:[...new Set(reasons)]};}
function buildTestImpactMap({changedPaths=[],signals={},candidates=[],history={},maxTests=40,minScore=1}={}){const normalizedChanged=[...new Set((changedPaths||[]).map(normalizePath).filter(Boolean))];const ranked=[];for(const raw of candidates||[]){const candidate=normalizeTestCandidate(raw);if(!candidate)continue;const scored=candidateScore(candidate,normalizedChanged,signals,history);if(scored.score<minScore)continue;ranked.push({...candidate,score:scored.score,reasons:scored.reasons});}ranked.sort((a,b)=>b.score-a.score||a.path.localeCompare(b.path)||a.id.localeCompare(b.id));const selected=ranked.slice(0,Math.max(0,Math.min(200,Math.floor(Number(maxTests)||40))));const digest=sha(JSON.stringify({version:TEST_IMPACT_VERSION,changedPaths:normalizedChanged,tests:selected.map(({id,path,score,reasons})=>({id,path,score,reasons}))}));return freeze({version:TEST_IMPACT_VERSION,changedPaths:normalizedChanged,recommendedTests:selected.map(({content,relatedPaths,...test})=>test),candidateCount:ranked.length,truncated:selected.length<ranked.length,digest});}
function formatTestImpactEvidence(result,{maxBytes=48*1024}={}){if(!result?.recommendedTests?.length)return freeze({text:'',included:0,total:0,truncated:false,bytes:0});const lines=['--- TEST IMPACT EVIDENCE ---',`Changed paths: ${(result.changedPaths||[]).join(', ')}`];let included=0,bytes=Buffer.byteLength(lines.join('\n'),'utf8'),truncated=false;for(const test of result.recommendedTests){const line=`- ${test.id} (${test.path}) score=${test.score} reasons=${(test.reasons||[]).join(',')}`,size=Buffer.byteLength(`\n${line}`,'utf8');if(maxBytes>0&&bytes+size>maxBytes){truncated=true;break;}lines.push(line);bytes+=size;included++;}lines.push('--- END TEST IMPACT EVIDENCE ---');const text=lines.join('\n');return freeze({text,included,total:result.recommendedTests.length,truncated:truncated||included<result.recommendedTests.length,bytes:Buffer.byteLength(text,'utf8')});}

module.exports=Object.freeze({TEST_IMPACT_VERSION,normalizeTestCandidate,candidateScore,buildTestImpactMap,formatTestImpactEvidence});
