name: Quality Eval

on:
  workflow_dispatch:
  schedule:
    - cron: '17 4 * * 2'

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@e51e5fe84fc33b4c73ebe40526b2694712b5b858
        with:
          node-version: '22.22.2'
      - run: npm run quality
